AttributeError: 'NeuralNetClassifier' object has no attribute 'score' (#470)
NeuralNetClassifier, NeuralNetBinaryClassifier, and NeuralNetRegressor get a score method

They now have the same score method as their sklearn equivalents: accuracy for classifiers, R² for regressors. NeuralNet still does not implement a score method.